2023-12-17 13:37:20.671 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-17 13:37:20.673 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration smartir which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-12-17 13:48:31.499 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547301959488] Received invalid command: {'access_token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIxOTFhOGM1M2EzZDI0ZjZkYjhlYTk2ZGRlNDQ5NDUzNiIsImlhdCI6MTcwMjgzODkxMSwiZXhwIjoxNzAyODQwNzExfQ.-KLzJSd84cpbAn3u1GHs_ezvtXc1uwVFIMRzsev7OwI', 'type': 'auth'}
2023-12-17 15:33:31.255 WARNING (MainThread) [custom_components.smartir.climate] The temperature value is out of min/max range
2023-12-17 15:33:33.196 WARNING (MainThread) [custom_components.smartir.climate] The temperature value is out of min/max range
2023-12-17 15:33:37.390 WARNING (MainThread) [custom_components.smartir.climate] The temperature value is out of min/max range
2023-12-17 15:33:42.392 WARNING (MainThread) [custom_components.smartir.climate] The temperature value is out of min/max range
2023-12-17 15:33:45.446 WARNING (MainThread) [custom_components.smartir.climate] The temperature value is out of min/max range
2023-12-17 15:39:12.959 WARNING (MainThread) [custom_components.smartir.climate] The temperature value is out of min/max range
2023-12-17 15:43:29.616 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/sensors?forceUpdate=true'))
2023-12-17 15:43:29.618 ERROR (MainThread) [homeassistant.components.simplisafe] Error fetching 4409167 data: SimpliSafe error while updating: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/sensors?forceUpdate=true')
2023-12-17 15:46:30.004 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 15:49:29.533 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 15:52:29.808 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 15:55:29.716 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 15:58:29.682 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 16:01:30.143 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 16:04:30.664 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 16:07:31.491 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 16:10:32.330 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 16:13:34.419 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 16:16:34.669 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 16:19:34.067 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 16:22:34.851 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 16:25:35.460 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 16:28:35.620 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 16:31:36.024 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 16:34:43.509 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 16:37:44.192 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 16:40:46.543 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 16:43:46.551 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 16:46:46.090 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 16:49:46.760 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 16:52:48.586 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 16:55:48.393 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 16:58:48.775 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 17:01:49.376 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 17:04:49.244 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 17:07:49.648 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 17:10:49.615 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 17:18:01.112 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/sensors?forceUpdate=true'))
2023-12-17 17:18:01.114 ERROR (MainThread) [homeassistant.components.simplisafe] Error fetching 4409167 data: SimpliSafe error while updating: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/sensors?forceUpdate=true')
2023-12-17 17:21:15.659 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 17:24:15.503 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 17:27:15.657 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 17:30:15.920 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 17:30:23.159 WARNING (MainThread) [custom_components.smartir.climate] The temperature value is out of min/max range
2023-12-17 17:30:28.117 WARNING (MainThread) [custom_components.smartir.climate] The temperature value is out of min/max range
2023-12-17 17:30:29.732 WARNING (MainThread) [custom_components.smartir.climate] The temperature value is out of min/max range
2023-12-17 17:30:30.883 WARNING (MainThread) [custom_components.smartir.climate] The temperature value is out of min/max range
2023-12-17 17:30:38.506 WARNING (MainThread) [custom_components.smartir.climate] The temperature value is out of min/max range
2023-12-17 17:30:39.610 WARNING (MainThread) [custom_components.smartir.climate] The temperature value is out of min/max range
2023-12-17 17:30:40.844 WARNING (MainThread) [custom_components.smartir.climate] The temperature value is out of min/max range
2023-12-17 17:33:16.684 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 17:36:15.922 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 17:38:40.176 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 401, message='Unauthorized', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 17:41:41.777 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 17:44:41.472 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 17:47:41.908 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 17:50:42.047 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 17:53:42.716 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 17:56:42.039 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 17:59:42.308 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 18:02:43.230 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 18:05:43.588 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 18:08:43.952 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 18:11:43.889 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 18:14:43.470 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 18:17:43.987 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 18:20:43.007 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
2023-12-17 18:23:43.421 ERROR (MainThread) [simplipy] Giving up _async_api_request(...) after 4 tries (aiohttp.client_exceptions.ClientResponseError: 504, message='Gateway Timeout', url=URL('https://api.simplisafe.com/v1/ss3/subscriptions/4671543/settings/normal?forceUpdate=true'))
